import {
    Home,
    Info,
    Users,
    User,
    UserCheck,
    UserPlus,
    HelpCircle,
    Target,
    Heart,
    File,
    Lock,
    Layers,
    Briefcase,
    Shield,
    ShieldCheck,
    GraduationCap,
    Newspaper,
    HandHeart,
    FilePlus,
    CheckSquare,
    Scale,
    Folder,
    Factory,
    FileText,
    Edit3,
    CornerDownLeft,
    ClipboardList,
    Mail,
    ListChecks,
    BookOpen,
    Book,
    Calendar,
    CalendarDays,
    MailPlus,
    Handshake,
    HeartHandshake,
    Building2,
    Network,
    Megaphone,
    BarChart3,
    Phone,
    PhoneCall,
    MessageCircle,
    Search,
    Award,
    AlertTriangle,
    AlertOctagon,
    Clock,
    Repeat,
    RefreshCcw,
    CreditCard,
    Gavel,
    Landmark,
    Percent,
    CheckCircle,
    Cpu,
    Globe,
    Link2,
    Key,
    Anchor,
    Package,
    Ship,
    Image as ImageIcon,
    Send,
    Download,
    Video,
    LogIn,
    Bell,
    ToolCase,
    ShieldOff,
    LockOpen,
    AlertCircle,
    CornerUpRight,
    IdCard,
} from "lucide-react"

export const iconMap: Record<string, any> = {
    /* BASIC */
    home: Home,
    info: Info,
    users: Users,
    user: User,
    "user-check": UserCheck,
    "user-plus": UserPlus,

    /* ABOUT */
    "help-circle": HelpCircle,
    target: Target,
    heart: Heart,
    layers: Layers,
    briefcase: Briefcase,
    shield: Shield,
    "shield-check": ShieldCheck,
    "graduation-cap": GraduationCap,
    newspaper: Newspaper,

    /* LEGAL AID */
    "hand-heart": HandHeart,
    "file-plus": FilePlus,
    "check-square": CheckSquare,
    scale: Scale,
    folder: Folder,
    factory: Factory,
    "file-text": FileText,
    "edit-3": Edit3,
    "corner-down-left": CornerDownLeft,
    "clipboard-list": ClipboardList,
    mail: Mail,
    checklist: ListChecks,
    "book-open": BookOpen,
    calendar: Calendar,
    "mail-plus": MailPlus,
    search: Search,
    award: Award,

    /* SERVICES */
    "alert-triangle": AlertTriangle,
    "alert-octagon": AlertOctagon,
    clock: Clock,
    repeat: Repeat,
    "refresh-ccw": RefreshCcw,
    "credit-card": CreditCard,
    gavel: Gavel,
    landmark: Landmark,
    percent: Percent,
    "check-circle": CheckCircle,
    cpu: Cpu,
    globe: Globe,
    "link-2": Link2,
    key: Key,
    anchor: Anchor,
    package: Package,
    ship: Ship,
    lock:Lock,
    file:File,
    "shield-off":ShieldOff,
    "lock-open":LockOpen,
    "alert-circle":AlertCircle,
    "corner-up-right":CornerUpRight,


    /* MEMBERSHIP */
    star: CheckCircle,
    "calendar-days": CalendarDays,
    "log-in": LogIn,
    "id-card" : IdCard,

    /* AWARENESS */
    image: ImageIcon,
    send: Send,

    /* RESOURCES */
    download: Download,
    video: Video,
    tool: ToolCase,
    book: Book,
    bell: Bell,

    /* PARTNERS */
    handshake: Handshake,
    "heart-handshake": HeartHandshake,
    "building-2": Building2,
    network: Network,
    megaphone: Megaphone,
    "bar-chart-3": BarChart3,

    /* CONTACT */
    phone: Phone,
    "phone-call": PhoneCall,
    "message-circle": MessageCircle,
}
